fixed value distribution graph
NobodyForNothing/blood-pressure-monitor-fl pull request #324
Opened 2024-06-12 18:29 UTC by mrjspb

- fixed offset by one bug in case there is no measurements with valuemax-1
- fixed bar order in graph, map keys not sorted

2024-06-13 07:55 UTC, NobodyForNothing requested changes
Thanks for the great find!

Unfortunately your PR draws out of bounds (`assert(barDrawXOffset >= 0 && barDrawXOffset <= size.width)` fails). I'm also not sure where the math fails (probably you mixed up `.keys` and `.values` in the barNumber computation), but I think that we can hit two birds with one stone here.:

You could iterate over the values in the right order in the painter (l.141):
```dart
for (int xPos = distribution.keys.min; xPos <= distribution.keys.max; xPos++) {
```

and can remove the loop that had the off by one error entirely by defaulting to 0 for keys without value during length computation
```dart
final length = heightUnit * (distribution[xPos] ?? 0);
```

2024-06-13 11:08 UTC, mrjspb commented
> probably you mixed up `.keys` and `.values` in the barNumber computation

yep, seems so

> and can remove the loop that had the off by one error entirely

In this case I need to also fix around 120, where length used to calculate number of columns. I've been hoping to fix it easy way, since never written a line on dart :)
Though you are right, it's better to make it clean

2024-06-16 15:34 UTC, NobodyForNothing commented
@mrjspb I made the discussed changes myself. Could you double check that I got the math right this time?

2024-06-16 15:59 UTC, mrjspb commented
Ups, sorry, I have installed dart and been fixing it too.  Give me one day, please, I'll merge branches together and check

2024-06-16 17:58 UTC, mrjspb commented
@NobodyForNothing pushed, seems we have done almost the same changes, i have added a bit more asserts and changed type of the map

2024-06-18 12:05 UTC, NobodyForNothing commented
@mrjspb thanks for the fixes and the work you put in. Glad to hear our changes match.

I also updated the loop the `_average` getter and will get this merged once I confirm no tests fail.

2024-06-18 12:06 UTC, NobodyForNothing approved these changes

2024-06-18 12:07 UTC, merged